// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_sku_proto/sku_business/sku.proto

package sku_business

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
	RetCode_SKU_NOT_EXIST      RetCode = 50007
	RetCode_SKU_EXIST          RetCode = 50008
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "SHOP_NOT_EXIST",
	50006: "SHOP_EXIST",
	50007: "SKU_NOT_EXIST",
	50008: "SKU_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
	"SHOP_NOT_EXIST":     50005,
	"SHOP_EXIST":         50006,
	"SKU_NOT_EXIST":      50007,
	"SKU_EXIST":          50008,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
	4: "PUT_AWAY",
}

var OperationType_value = map[string]int32{
	"CREATE":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"AUDIT":    3,
	"PUT_AWAY": 4,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{1}
}

type GetSkuListRequest struct {
	ShopId               int64    `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSkuListRequest) Reset()         { *m = GetSkuListRequest{} }
func (m *GetSkuListRequest) String() string { return proto.CompactTextString(m) }
func (*GetSkuListRequest) ProtoMessage()    {}
func (*GetSkuListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{0}
}

func (m *GetSkuListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSkuListRequest.Unmarshal(m, b)
}
func (m *GetSkuListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSkuListRequest.Marshal(b, m, deterministic)
}
func (m *GetSkuListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSkuListRequest.Merge(m, src)
}
func (m *GetSkuListRequest) XXX_Size() int {
	return xxx_messageInfo_GetSkuListRequest.Size(m)
}
func (m *GetSkuListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSkuListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSkuListRequest proto.InternalMessageInfo

func (m *GetSkuListRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetSkuListResponse struct {
	List                 []*SkuInventoryInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSkuListResponse) Reset()         { *m = GetSkuListResponse{} }
func (m *GetSkuListResponse) String() string { return proto.CompactTextString(m) }
func (*GetSkuListResponse) ProtoMessage()    {}
func (*GetSkuListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{1}
}

func (m *GetSkuListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSkuListResponse.Unmarshal(m, b)
}
func (m *GetSkuListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSkuListResponse.Marshal(b, m, deterministic)
}
func (m *GetSkuListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSkuListResponse.Merge(m, src)
}
func (m *GetSkuListResponse) XXX_Size() int {
	return xxx_messageInfo_GetSkuListResponse.Size(m)
}
func (m *GetSkuListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSkuListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSkuListResponse proto.InternalMessageInfo

func (m *GetSkuListResponse) GetList() []*SkuInventoryInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 商品库存数据
type SkuInventoryInfo struct {
	SkuCode              string   `protobuf:"bytes,1,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle             string   `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Production           string   `protobuf:"bytes,7,opt,name=production,proto3" json:"production,omitempty"`
	Supplier             string   `protobuf:"bytes,8,opt,name=supplier,proto3" json:"supplier,omitempty"`
	Category             int32    `protobuf:"varint,9,opt,name=category,proto3" json:"category,omitempty"`
	Color                string   `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	ColorCode            int32    `protobuf:"varint,11,opt,name=color_code,json=colorCode,proto3" json:"color_code,omitempty"`
	Specification        string   `protobuf:"bytes,12,opt,name=specification,proto3" json:"specification,omitempty"`
	DescLink             string   `protobuf:"bytes,13,opt,name=desc_link,json=descLink,proto3" json:"desc_link,omitempty"`
	State                int32    `protobuf:"varint,14,opt,name=state,proto3" json:"state,omitempty"`
	Amount               int64    `protobuf:"varint,198,opt,name=amount,proto3" json:"amount,omitempty"`
	ShopId               int64    `protobuf:"varint,199,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkuInventoryInfo) Reset()         { *m = SkuInventoryInfo{} }
func (m *SkuInventoryInfo) String() string { return proto.CompactTextString(m) }
func (*SkuInventoryInfo) ProtoMessage()    {}
func (*SkuInventoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{2}
}

func (m *SkuInventoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkuInventoryInfo.Unmarshal(m, b)
}
func (m *SkuInventoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkuInventoryInfo.Marshal(b, m, deterministic)
}
func (m *SkuInventoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkuInventoryInfo.Merge(m, src)
}
func (m *SkuInventoryInfo) XXX_Size() int {
	return xxx_messageInfo_SkuInventoryInfo.Size(m)
}
func (m *SkuInventoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SkuInventoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SkuInventoryInfo proto.InternalMessageInfo

func (m *SkuInventoryInfo) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *SkuInventoryInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SkuInventoryInfo) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *SkuInventoryInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SkuInventoryInfo) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *SkuInventoryInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SkuInventoryInfo) GetProduction() string {
	if m != nil {
		return m.Production
	}
	return ""
}

func (m *SkuInventoryInfo) GetSupplier() string {
	if m != nil {
		return m.Supplier
	}
	return ""
}

func (m *SkuInventoryInfo) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *SkuInventoryInfo) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *SkuInventoryInfo) GetColorCode() int32 {
	if m != nil {
		return m.ColorCode
	}
	return 0
}

func (m *SkuInventoryInfo) GetSpecification() string {
	if m != nil {
		return m.Specification
	}
	return ""
}

func (m *SkuInventoryInfo) GetDescLink() string {
	if m != nil {
		return m.DescLink
	}
	return ""
}

func (m *SkuInventoryInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SkuInventoryInfo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SkuInventoryInfo) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type PutAwaySkuRequest struct {
	OpUid                int64             `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
	OpIp                 string            `protobuf:"bytes,2,opt,name=op_ip,json=opIp,proto3" json:"op_ip,omitempty"`
	Sku                  *SkuInventoryInfo `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	OperationType        OperationType     `protobuf:"varint,299,opt,name=operation_type,json=operationType,proto3,enum=sku_business.OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutAwaySkuRequest) Reset()         { *m = PutAwaySkuRequest{} }
func (m *PutAwaySkuRequest) String() string { return proto.CompactTextString(m) }
func (*PutAwaySkuRequest) ProtoMessage()    {}
func (*PutAwaySkuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{3}
}

func (m *PutAwaySkuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAwaySkuRequest.Unmarshal(m, b)
}
func (m *PutAwaySkuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAwaySkuRequest.Marshal(b, m, deterministic)
}
func (m *PutAwaySkuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAwaySkuRequest.Merge(m, src)
}
func (m *PutAwaySkuRequest) XXX_Size() int {
	return xxx_messageInfo_PutAwaySkuRequest.Size(m)
}
func (m *PutAwaySkuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAwaySkuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutAwaySkuRequest proto.InternalMessageInfo

func (m *PutAwaySkuRequest) GetOpUid() int64 {
	if m != nil {
		return m.OpUid
	}
	return 0
}

func (m *PutAwaySkuRequest) GetOpIp() string {
	if m != nil {
		return m.OpIp
	}
	return ""
}

func (m *PutAwaySkuRequest) GetSku() *SkuInventoryInfo {
	if m != nil {
		return m.Sku
	}
	return nil
}

func (m *PutAwaySkuRequest) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_CREATE
}

type PutAwaySkuResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutAwaySkuResponse) Reset()         { *m = PutAwaySkuResponse{} }
func (m *PutAwaySkuResponse) String() string { return proto.CompactTextString(m) }
func (*PutAwaySkuResponse) ProtoMessage()    {}
func (*PutAwaySkuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{4}
}

func (m *PutAwaySkuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAwaySkuResponse.Unmarshal(m, b)
}
func (m *PutAwaySkuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAwaySkuResponse.Marshal(b, m, deterministic)
}
func (m *PutAwaySkuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAwaySkuResponse.Merge(m, src)
}
func (m *PutAwaySkuResponse) XXX_Size() int {
	return xxx_messageInfo_PutAwaySkuResponse.Size(m)
}
func (m *PutAwaySkuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAwaySkuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutAwaySkuResponse proto.InternalMessageInfo

func (m *PutAwaySkuResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=sku_business.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8802e7d0015e41f9, []int{5}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("sku_business.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("sku_business.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*GetSkuListRequest)(nil), "sku_business.GetSkuListRequest")
	proto.RegisterType((*GetSkuListResponse)(nil), "sku_business.GetSkuListResponse")
	proto.RegisterType((*SkuInventoryInfo)(nil), "sku_business.SkuInventoryInfo")
	proto.RegisterType((*PutAwaySkuRequest)(nil), "sku_business.PutAwaySkuRequest")
	proto.RegisterType((*PutAwaySkuResponse)(nil), "sku_business.PutAwaySkuResponse")
	proto.RegisterType((*CommonResponse)(nil), "sku_business.CommonResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_sku_proto/sku_business/sku.proto", fileDescriptor_8802e7d0015e41f9)
}

var fileDescriptor_8802e7d0015e41f9 = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcf, 0x72, 0xe3, 0xc4,
	0x13, 0xfe, 0x29, 0xf2, 0xdf, 0x4e, 0xec, 0x9f, 0xb6, 0x37, 0xa9, 0x15, 0x09, 0x2c, 0x29, 0x17,
	0x87, 0x90, 0x82, 0x98, 0x35, 0x9c, 0x38, 0x50, 0x65, 0x1c, 0x15, 0x31, 0x64, 0x37, 0x29, 0x49,
	0x2e, 0xe0, 0xa4, 0x52, 0xe4, 0x59, 0x33, 0x25, 0x59, 0x33, 0x68, 0x46, 0xd9, 0xf2, 0x95, 0x83,
	0x5f, 0x80, 0xc7, 0xe0, 0x0e, 0x6f, 0x00, 0x5c, 0x61, 0xf9, 0xf7, 0x00, 0x5c, 0xb8, 0xf3, 0x00,
	0xd4, 0xcc, 0xd8, 0x89, 0x9c, 0x14, 0xc5, 0xad, 0xfb, 0xeb, 0x6f, 0xbe, 0xee, 0x99, 0xee, 0x69,
	0x78, 0xc2, 0x0b, 0x26, 0x59, 0x7f, 0x4e, 0x93, 0x82, 0x45, 0xf3, 0x38, 0xcb, 0x22, 0x91, 0x96,
	0x91, 0x01, 0x95, 0x75, 0x55, 0x0a, 0x9a, 0x13, 0x21, 0x94, 0x73, 0xa2, 0x61, 0xdc, 0xa9, 0xe2,
	0xfb, 0x1f, 0xcc, 0xa8, 0x24, 0xe4, 0x24, 0x61, 0xf3, 0x7e, 0x4a, 0xb2, 0x6b, 0x9a, 0x8b, 0xb7,
	0x29, 0xeb, 0x27, 0x6c, 0x3e, 0x67, 0x79, 0xdf, 0xe8, 0xcc, 0x18, 0x9b, 0x65, 0xa4, 0x1f, 0x73,
	0xda, 0x8f, 0xf3, 0x9c, 0xc9, 0x58, 0x52, 0x96, 0x0b, 0xa3, 0xd6, 0x7b, 0x0b, 0x1e, 0x7c, 0x44,
	0x64, 0x90, 0x96, 0xe7, 0x54, 0x48, 0x9f, 0x7c, 0x59, 0x12, 0x21, 0xf1, 0x11, 0x34, 0xc5, 0x17,
	0x8c, 0x47, 0x74, 0xea, 0x5a, 0x87, 0xd6, 0x91, 0xed, 0x37, 0x94, 0x3b, 0x9e, 0xf6, 0xce, 0x00,
	0xab, 0x6c, 0xc1, 0x59, 0x2e, 0x08, 0x0e, 0xa0, 0x96, 0x51, 0x21, 0x5d, 0xeb, 0xd0, 0x3e, 0xda,
	0x1e, 0x3c, 0x3e, 0xa9, 0x16, 0x78, 0x12, 0xa4, 0xe5, 0x38, 0xbf, 0x26, 0xb9, 0x64, 0xc5, 0x62,
	0x9c, 0x3f, 0x67, 0xbe, 0xe6, 0xf6, 0xbe, 0xb3, 0xc1, 0xb9, 0x1b, 0xc2, 0x57, 0xa0, 0xa5, 0xce,
	0x26, 0x6c, 0x4a, 0x74, 0xe2, 0xb6, 0xdf, 0x14, 0x69, 0x39, 0x62, 0x53, 0x82, 0x08, 0xb5, 0x3c,
	0x9e, 0x13, 0x77, 0x4b, 0xc3, 0xda, 0xc6, 0x5d, 0xa8, 0xf3, 0x82, 0x26, 0xc4, 0xb5, 0x35, 0x68,
	0x1c, 0x85, 0x4a, 0x2a, 0x33, 0xe2, 0xd6, 0x0c, 0xaa, 0x1d, 0x3c, 0x80, 0xb6, 0x28, 0xaf, 0x22,
	0x13, 0xa9, 0xeb, 0x48, 0x4b, 0x94, 0x57, 0xa1, 0x0e, 0x22, 0xd4, 0xa6, 0x44, 0x24, 0x6e, 0xc3,
	0x88, 0x2b, 0x1b, 0x1f, 0x03, 0xf0, 0x82, 0x4d, 0xcb, 0x44, 0xbd, 0x96, 0xdb, 0xd4, 0x91, 0x0a,
	0x82, 0xfb, 0xd0, 0x12, 0x25, 0xe7, 0x19, 0x25, 0x85, 0xdb, 0x5a, 0xeb, 0x19, 0x5f, 0xc5, 0x92,
	0x58, 0x92, 0x19, 0x2b, 0x16, 0x6e, 0xfb, 0xd0, 0x3a, 0xaa, 0xfb, 0x37, 0xbe, 0x2a, 0x2f, 0x61,
	0x19, 0x2b, 0x5c, 0x30, 0xe5, 0x69, 0x07, 0x5f, 0x03, 0xd0, 0x86, 0xb9, 0xfb, 0xb6, 0x3e, 0xd3,
	0xd6, 0x88, 0xbe, 0xfd, 0x1b, 0xd0, 0x11, 0x9c, 0x24, 0xf4, 0x39, 0x4d, 0x74, 0xf7, 0xdc, 0x1d,
	0x7d, 0x78, 0x13, 0x54, 0x77, 0x54, 0xa5, 0x47, 0x19, 0xcd, 0x53, 0xb7, 0x63, 0x6a, 0x52, 0xc0,
	0x39, 0xcd, 0x53, 0x95, 0x57, 0xc8, 0x58, 0x12, 0xb7, 0xab, 0xc5, 0x8d, 0x83, 0x8f, 0xa0, 0x11,
	0xcf, 0x59, 0x99, 0x4b, 0xf7, 0xfb, 0x55, 0xa7, 0x8d, 0x8b, 0xee, 0xed, 0x08, 0xfc, 0xb0, 0x39,
	0x03, 0xdf, 0x5a, 0xf0, 0xe0, 0xb2, 0x94, 0xc3, 0x17, 0xf1, 0x22, 0x48, 0xcb, 0xf5, 0xc8, 0xec,
	0x41, 0x83, 0xf1, 0xa8, 0xbc, 0x99, 0x98, 0x3a, 0xe3, 0x13, 0x3a, 0xc5, 0x87, 0x50, 0x57, 0x22,
	0x7c, 0xdd, 0x37, 0xc6, 0xc7, 0x1c, 0xdf, 0x01, 0x5b, 0xa4, 0xa5, 0xee, 0xda, 0x7f, 0x8f, 0x8b,
	0xa2, 0xe2, 0x08, 0xba, 0x8c, 0x93, 0x42, 0x5f, 0x33, 0x92, 0x0b, 0x4e, 0xdc, 0x6f, 0x94, 0x60,
	0x77, 0x70, 0xb0, 0x79, 0xfa, 0x62, 0x4d, 0x0a, 0x17, 0x9c, 0xf8, 0x1d, 0x56, 0x75, 0x7b, 0x1f,
	0x03, 0x56, 0xeb, 0x5e, 0x0d, 0xef, 0x7b, 0xd0, 0x30, 0xbf, 0x45, 0x17, 0xbe, 0x3d, 0x78, 0x75,
	0x53, 0x71, 0xa4, 0x63, 0x6b, 0xb6, 0xbf, 0xe2, 0xf6, 0x9e, 0x42, 0x77, 0x33, 0x82, 0x6f, 0x42,
	0xed, 0x66, 0x6e, 0xbb, 0x83, 0xbd, 0x4d, 0x15, 0x9f, 0x48, 0xd5, 0x47, 0x5f, 0x53, 0xd0, 0x01,
	0x7b, 0x2e, 0x66, 0xab, 0x27, 0x51, 0xe6, 0xf1, 0x8f, 0x16, 0x34, 0x57, 0x1c, 0xdc, 0x86, 0x66,
	0x30, 0x19, 0x8d, 0xbc, 0x20, 0x70, 0xfe, 0x87, 0x00, 0x75, 0xcf, 0xf7, 0x2f, 0x7c, 0xe7, 0x6f,
	0x1b, 0x77, 0xa1, 0x3b, 0x09, 0x3c, 0x3f, 0x7a, 0x76, 0x11, 0x46, 0xde, 0x67, 0xe3, 0x20, 0x74,
	0x7e, 0x5a, 0xda, 0xe8, 0x00, 0x68, 0xd4, 0x20, 0x3f, 0x2f, 0x6d, 0x74, 0x01, 0x9f, 0x7a, 0xfe,
	0xe8, 0x6c, 0xf8, 0x2c, 0xac, 0x70, 0x5f, 0x2e, 0xb5, 0xc2, 0x4d, 0xc4, 0xa0, 0xbf, 0x18, 0x34,
	0x38, 0xbb, 0xb8, 0xac, 0x70, 0x7f, 0x35, 0xba, 0x1a, 0x35, 0xc8, 0x6f, 0x4b, 0x1b, 0x1f, 0x42,
	0x27, 0xf8, 0x64, 0x52, 0xa1, 0xfd, 0xbe, 0xb4, 0xf1, 0xff, 0xd0, 0x56, 0xa0, 0x01, 0xfe, 0x58,
	0xda, 0xc7, 0xe7, 0xd0, 0xd9, 0xe8, 0x02, 0x02, 0x34, 0x46, 0xbe, 0x37, 0x0c, 0x3d, 0x7d, 0x9d,
	0xc6, 0xe4, 0xf2, 0x54, 0xd9, 0x96, 0xb2, 0x4f, 0xbd, 0x73, 0x2f, 0xf4, 0x9c, 0x2d, 0x6c, 0x43,
	0x7d, 0x38, 0x39, 0x1d, 0x87, 0x8e, 0x8d, 0x3b, 0xd0, 0xba, 0x9c, 0x84, 0xd1, 0xf0, 0xd3, 0xe1,
	0xe7, 0x4e, 0x6d, 0xf0, 0x97, 0x05, 0x18, 0xa4, 0xe5, 0x87, 0xab, 0x87, 0x0c, 0x48, 0x71, 0xad,
	0xfe, 0x78, 0x06, 0x70, 0xdb, 0x4a, 0x7c, 0x7d, 0xf3, 0xb1, 0xef, 0x0d, 0xe7, 0xfe, 0xe1, 0xbf,
	0x13, 0x4c, 0xf7, 0x7a, 0x07, 0x5f, 0xbd, 0xfc, 0xf3, 0xeb, 0xad, 0xbd, 0x9e, 0xd3, 0xbf, 0x7e,
	0xa2, 0x76, 0x6d, 0x9f, 0x97, 0x32, 0x8a, 0x5f, 0xc4, 0x8b, 0xf7, 0xad, 0x63, 0x24, 0x00, 0xb7,
	0x5b, 0xef, 0x6e, 0xb6, 0x7b, 0xdb, 0xf3, 0x6e, 0xb6, 0xfb, 0x0b, 0xb3, 0xb7, 0xab, 0xb3, 0x75,
	0x71, 0x67, 0x9d, 0x4d, 0xad, 0xc4, 0xab, 0x86, 0xde, 0xc8, 0xef, 0xfe, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0x64, 0x5a, 0x06, 0x14, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SkuBusinessServiceClient is the client API for SkuBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SkuBusinessServiceClient interface {
	// 上架商品
	PutAwaySku(ctx context.Context, in *PutAwaySkuRequest, opts ...grpc.CallOption) (*PutAwaySkuResponse, error)
	GetSkuList(ctx context.Context, in *GetSkuListRequest, opts ...grpc.CallOption) (*GetSkuListResponse, error)
}

type skuBusinessServiceClient struct {
	cc *grpc.ClientConn
}

func NewSkuBusinessServiceClient(cc *grpc.ClientConn) SkuBusinessServiceClient {
	return &skuBusinessServiceClient{cc}
}

func (c *skuBusinessServiceClient) PutAwaySku(ctx context.Context, in *PutAwaySkuRequest, opts ...grpc.CallOption) (*PutAwaySkuResponse, error) {
	out := new(PutAwaySkuResponse)
	err := c.cc.Invoke(ctx, "/sku_business.SkuBusinessService/PutAwaySku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuBusinessServiceClient) GetSkuList(ctx context.Context, in *GetSkuListRequest, opts ...grpc.CallOption) (*GetSkuListResponse, error) {
	out := new(GetSkuListResponse)
	err := c.cc.Invoke(ctx, "/sku_business.SkuBusinessService/GetSkuList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuBusinessServiceServer is the server API for SkuBusinessService service.
type SkuBusinessServiceServer interface {
	// 上架商品
	PutAwaySku(context.Context, *PutAwaySkuRequest) (*PutAwaySkuResponse, error)
	GetSkuList(context.Context, *GetSkuListRequest) (*GetSkuListResponse, error)
}

// UnimplementedSkuBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSkuBusinessServiceServer struct {
}

func (*UnimplementedSkuBusinessServiceServer) PutAwaySku(ctx context.Context, req *PutAwaySkuRequest) (*PutAwaySkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAwaySku not implemented")
}
func (*UnimplementedSkuBusinessServiceServer) GetSkuList(ctx context.Context, req *GetSkuListRequest) (*GetSkuListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkuList not implemented")
}

func RegisterSkuBusinessServiceServer(s *grpc.Server, srv SkuBusinessServiceServer) {
	s.RegisterService(&_SkuBusinessService_serviceDesc, srv)
}

func _SkuBusinessService_PutAwaySku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAwaySkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuBusinessServiceServer).PutAwaySku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sku_business.SkuBusinessService/PutAwaySku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuBusinessServiceServer).PutAwaySku(ctx, req.(*PutAwaySkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuBusinessService_GetSkuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkuListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuBusinessServiceServer).GetSkuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sku_business.SkuBusinessService/GetSkuList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuBusinessServiceServer).GetSkuList(ctx, req.(*GetSkuListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SkuBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sku_business.SkuBusinessService",
	HandlerType: (*SkuBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutAwaySku",
			Handler:    _SkuBusinessService_PutAwaySku_Handler,
		},
		{
			MethodName: "GetSkuList",
			Handler:    _SkuBusinessService_GetSkuList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_sku_proto/sku_business/sku.proto",
}
