// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_users_proto/users/users.proto

package users

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
	OperationType_AUDIT  OperationType = 3
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
}

var OperationType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
	"AUDIT":  3,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{1}
}

type GetUserInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{0}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	CountryCode          string   `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	State                int32    `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	IdCardNo             string   `protobuf:"bytes,9,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	Inviter              int64    `protobuf:"varint,10,opt,name=inviter,proto3" json:"inviter,omitempty"`
	InviterCode          string   `protobuf:"bytes,11,opt,name=inviter_code,json=inviterCode,proto3" json:"inviter_code,omitempty"`
	ContactAddr          string   `protobuf:"bytes,12,opt,name=contact_addr,json=contactAddr,proto3" json:"contact_addr,omitempty"`
	Age                  int32    `protobuf:"varint,13,opt,name=age,proto3" json:"age,omitempty"`
	CreateTime           string   `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UserInfo) GetIdCardNo() string {
	if m != nil {
		return m.IdCardNo
	}
	return ""
}

func (m *UserInfo) GetInviter() int64 {
	if m != nil {
		return m.Inviter
	}
	return 0
}

func (m *UserInfo) GetInviterCode() string {
	if m != nil {
		return m.InviterCode
	}
	return ""
}

func (m *UserInfo) GetContactAddr() string {
	if m != nil {
		return m.ContactAddr
	}
	return ""
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type GetUserInfoResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info                 *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{2}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetUserInfoResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MerchantsMaterialInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MaterialId           int64    `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	RegisterAddr         string   `protobuf:"bytes,3,opt,name=register_addr,json=registerAddr,proto3" json:"register_addr,omitempty"`
	HealthCardNo         string   `protobuf:"bytes,4,opt,name=health_card_no,json=healthCardNo,proto3" json:"health_card_no,omitempty"`
	Identity             int32    `protobuf:"varint,5,opt,name=identity,proto3" json:"identity,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	TaxCardNo            string   `protobuf:"bytes,7,opt,name=tax_card_no,json=taxCardNo,proto3" json:"tax_card_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsMaterialInfo) Reset()         { *m = MerchantsMaterialInfo{} }
func (m *MerchantsMaterialInfo) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialInfo) ProtoMessage()    {}
func (*MerchantsMaterialInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{3}
}

func (m *MerchantsMaterialInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialInfo.Unmarshal(m, b)
}
func (m *MerchantsMaterialInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialInfo.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialInfo.Merge(m, src)
}
func (m *MerchantsMaterialInfo) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialInfo.Size(m)
}
func (m *MerchantsMaterialInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialInfo proto.InternalMessageInfo

func (m *MerchantsMaterialInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetRegisterAddr() string {
	if m != nil {
		return m.RegisterAddr
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetHealthCardNo() string {
	if m != nil {
		return m.HealthCardNo
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetIdentity() int32 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetTaxCardNo() string {
	if m != nil {
		return m.TaxCardNo
	}
	return ""
}

type MerchantsMaterialRequest struct {
	Info                 *MerchantsMaterialInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	OperationType        OperationType          `protobuf:"varint,2,opt,name=operation_type,json=operationType,proto3,enum=users.OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MerchantsMaterialRequest) Reset()         { *m = MerchantsMaterialRequest{} }
func (m *MerchantsMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialRequest) ProtoMessage()    {}
func (*MerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{4}
}

func (m *MerchantsMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialRequest.Unmarshal(m, b)
}
func (m *MerchantsMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialRequest.Merge(m, src)
}
func (m *MerchantsMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialRequest.Size(m)
}
func (m *MerchantsMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialRequest proto.InternalMessageInfo

func (m *MerchantsMaterialRequest) GetInfo() *MerchantsMaterialInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MerchantsMaterialRequest) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_CREATE
}

type MerchantsMaterialResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	MaterialId           int64           `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsMaterialResponse) Reset()         { *m = MerchantsMaterialResponse{} }
func (m *MerchantsMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialResponse) ProtoMessage()    {}
func (*MerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{5}
}

func (m *MerchantsMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialResponse.Unmarshal(m, b)
}
func (m *MerchantsMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialResponse.Merge(m, src)
}
func (m *MerchantsMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialResponse.Size(m)
}
func (m *MerchantsMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialResponse proto.InternalMessageInfo

func (m *MerchantsMaterialResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *MerchantsMaterialResponse) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

type GetMerchantsMaterialRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMerchantsMaterialRequest) Reset()         { *m = GetMerchantsMaterialRequest{} }
func (m *GetMerchantsMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*GetMerchantsMaterialRequest) ProtoMessage()    {}
func (*GetMerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{6}
}

func (m *GetMerchantsMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Unmarshal(m, b)
}
func (m *GetMerchantsMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Marshal(b, m, deterministic)
}
func (m *GetMerchantsMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantsMaterialRequest.Merge(m, src)
}
func (m *GetMerchantsMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Size(m)
}
func (m *GetMerchantsMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantsMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantsMaterialRequest proto.InternalMessageInfo

func (m *GetMerchantsMaterialRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

type GetMerchantsMaterialResponse struct {
	Common               *CommonResponse        `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info                 *MerchantsMaterialInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetMerchantsMaterialResponse) Reset()         { *m = GetMerchantsMaterialResponse{} }
func (m *GetMerchantsMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*GetMerchantsMaterialResponse) ProtoMessage()    {}
func (*GetMerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{7}
}

func (m *GetMerchantsMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Unmarshal(m, b)
}
func (m *GetMerchantsMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Marshal(b, m, deterministic)
}
func (m *GetMerchantsMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantsMaterialResponse.Merge(m, src)
}
func (m *GetMerchantsMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Size(m)
}
func (m *GetMerchantsMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantsMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantsMaterialResponse proto.InternalMessageInfo

func (m *GetMerchantsMaterialResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetMerchantsMaterialResponse) GetInfo() *MerchantsMaterialInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MerchantsAssociateShopRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IsAssociate          bool     `protobuf:"varint,3,opt,name=is_associate,json=isAssociate,proto3" json:"is_associate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsAssociateShopRequest) Reset()         { *m = MerchantsAssociateShopRequest{} }
func (m *MerchantsAssociateShopRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsAssociateShopRequest) ProtoMessage()    {}
func (*MerchantsAssociateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{8}
}

func (m *MerchantsAssociateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Unmarshal(m, b)
}
func (m *MerchantsAssociateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsAssociateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsAssociateShopRequest.Merge(m, src)
}
func (m *MerchantsAssociateShopRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Size(m)
}
func (m *MerchantsAssociateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsAssociateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsAssociateShopRequest proto.InternalMessageInfo

func (m *MerchantsAssociateShopRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsAssociateShopRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *MerchantsAssociateShopRequest) GetIsAssociate() bool {
	if m != nil {
		return m.IsAssociate
	}
	return false
}

type MerchantsAssociateShopResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsAssociateShopResponse) Reset()         { *m = MerchantsAssociateShopResponse{} }
func (m *MerchantsAssociateShopResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsAssociateShopResponse) ProtoMessage()    {}
func (*MerchantsAssociateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{9}
}

func (m *MerchantsAssociateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Unmarshal(m, b)
}
func (m *MerchantsAssociateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsAssociateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsAssociateShopResponse.Merge(m, src)
}
func (m *MerchantsAssociateShopResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Size(m)
}
func (m *MerchantsAssociateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsAssociateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsAssociateShopResponse proto.InternalMessageInfo

func (m *MerchantsAssociateShopResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

type MerchantsMaterialAuditRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	AuditUid             int64    `protobuf:"varint,2,opt,name=audit_uid,json=auditUid,proto3" json:"audit_uid,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsMaterialAuditRequest) Reset()         { *m = MerchantsMaterialAuditRequest{} }
func (m *MerchantsMaterialAuditRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialAuditRequest) ProtoMessage()    {}
func (*MerchantsMaterialAuditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{10}
}

func (m *MerchantsMaterialAuditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Unmarshal(m, b)
}
func (m *MerchantsMaterialAuditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialAuditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialAuditRequest.Merge(m, src)
}
func (m *MerchantsMaterialAuditRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Size(m)
}
func (m *MerchantsMaterialAuditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialAuditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialAuditRequest proto.InternalMessageInfo

func (m *MerchantsMaterialAuditRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsMaterialAuditRequest) GetAuditUid() int64 {
	if m != nil {
		return m.AuditUid
	}
	return 0
}

func (m *MerchantsMaterialAuditRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type MerchantsMaterialAuditResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	State                int32           `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Comment              string          `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	NextAuditUid         int64           `protobuf:"varint,4,opt,name=next_audit_uid,json=nextAuditUid,proto3" json:"next_audit_uid,omitempty"`
	IsOver               bool            `protobuf:"varint,5,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsMaterialAuditResponse) Reset()         { *m = MerchantsMaterialAuditResponse{} }
func (m *MerchantsMaterialAuditResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialAuditResponse) ProtoMessage()    {}
func (*MerchantsMaterialAuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{11}
}

func (m *MerchantsMaterialAuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Unmarshal(m, b)
}
func (m *MerchantsMaterialAuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialAuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialAuditResponse.Merge(m, src)
}
func (m *MerchantsMaterialAuditResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Size(m)
}
func (m *MerchantsMaterialAuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialAuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialAuditResponse proto.InternalMessageInfo

func (m *MerchantsMaterialAuditResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *MerchantsMaterialAuditResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *MerchantsMaterialAuditResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *MerchantsMaterialAuditResponse) GetNextAuditUid() int64 {
	if m != nil {
		return m.NextAuditUid
	}
	return 0
}

func (m *MerchantsMaterialAuditResponse) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=users.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{12}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("users.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("users.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*GetUserInfoRequest)(nil), "users.GetUserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "users.UserInfo")
	proto.RegisterType((*GetUserInfoResponse)(nil), "users.GetUserInfoResponse")
	proto.RegisterType((*MerchantsMaterialInfo)(nil), "users.MerchantsMaterialInfo")
	proto.RegisterType((*MerchantsMaterialRequest)(nil), "users.MerchantsMaterialRequest")
	proto.RegisterType((*MerchantsMaterialResponse)(nil), "users.MerchantsMaterialResponse")
	proto.RegisterType((*GetMerchantsMaterialRequest)(nil), "users.GetMerchantsMaterialRequest")
	proto.RegisterType((*GetMerchantsMaterialResponse)(nil), "users.GetMerchantsMaterialResponse")
	proto.RegisterType((*MerchantsAssociateShopRequest)(nil), "users.MerchantsAssociateShopRequest")
	proto.RegisterType((*MerchantsAssociateShopResponse)(nil), "users.MerchantsAssociateShopResponse")
	proto.RegisterType((*MerchantsMaterialAuditRequest)(nil), "users.MerchantsMaterialAuditRequest")
	proto.RegisterType((*MerchantsMaterialAuditResponse)(nil), "users.MerchantsMaterialAuditResponse")
	proto.RegisterType((*CommonResponse)(nil), "users.CommonResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_users_proto/users/users.proto", fileDescriptor_eb9de2f1fdeb7bca)
}

var fileDescriptor_eb9de2f1fdeb7bca = []byte{
	// 1112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0xe7, 0xe2, 0xff, 0xe3, 0xc4, 0x35, 0x4b, 0x4a, 0xaf, 0x4e, 0xd3, 0xa4, 0x97, 0x12, 0x45,
	0x11, 0x8d, 0x4b, 0xf8, 0x56, 0xa4, 0x48, 0x96, 0x63, 0x8a, 0x25, 0x92, 0xa0, 0xb3, 0x2d, 0x21,
	0xf1, 0xe1, 0xb4, 0xdc, 0x4d, 0xed, 0x55, 0x7c, 0xb7, 0xe6, 0x6e, 0x6d, 0x12, 0x84, 0x40, 0x42,
	0x28, 0x12, 0x7c, 0xed, 0x13, 0xf0, 0x1e, 0x88, 0x77, 0x80, 0xf2, 0x08, 0x48, 0xbc, 0x00, 0x0f,
	0x80, 0x76, 0xf7, 0xee, 0x62, 0xd7, 0x76, 0x1b, 0xe5, 0x8b, 0xb5, 0xfb, 0x9b, 0x99, 0xdd, 0xdf,
	0xfc, 0x76, 0x66, 0x7c, 0x70, 0x30, 0x0a, 0xb9, 0xe0, 0x75, 0x9f, 0xb9, 0x21, 0x77, 0x7c, 0x3a,
	0x1c, 0x3a, 0xe3, 0x08, 0xc3, 0xc8, 0xd1, 0xb0, 0x5a, 0xeb, 0x5f, 0xed, 0x48, 0x72, 0x6a, 0x53,
	0x3b, 0xea, 0x33, 0x81, 0x78, 0xe0, 0x72, 0xbf, 0x7e, 0x8e, 0xc3, 0x09, 0x0b, 0xa2, 0x27, 0x8c,
	0xd7, 0x5d, 0xee, 0xfb, 0x3c, 0xa8, 0xeb, 0xd8, 0x3e, 0xe7, 0xfd, 0x21, 0xd6, 0xe9, 0x88, 0xd5,
	0x69, 0x10, 0x70, 0x41, 0x05, 0xe3, 0x41, 0x7c, 0x8c, 0xb5, 0x0b, 0xe4, 0x39, 0x8a, 0x5e, 0x84,
	0x61, 0x3b, 0x78, 0xc1, 0x6d, 0xfc, 0x66, 0x8c, 0x91, 0x20, 0x55, 0xc8, 0x8c, 0x99, 0x67, 0x1a,
	0xdb, 0xc6, 0x5e, 0xc6, 0x96, 0x4b, 0xeb, 0xb7, 0x0c, 0x14, 0x13, 0xaf, 0x79, 0x33, 0xd9, 0x04,
	0xa0, 0xae, 0xcb, 0xc7, 0x81, 0x70, 0x98, 0x67, 0xae, 0x6c, 0x1b, 0x7b, 0x25, 0xbb, 0x14, 0x23,
	0x6d, 0x8f, 0x6c, 0x40, 0x49, 0xd2, 0x75, 0x02, 0xea, 0xa3, 0x99, 0x51, 0xd6, 0xa2, 0x04, 0x4e,
	0xa9, 0x8f, 0xf2, 0xb4, 0x08, 0x2f, 0xcc, 0xec, 0xb6, 0xb1, 0x97, 0xb3, 0xe5, 0x92, 0x3c, 0x82,
	0x55, 0x15, 0x19, 0x5e, 0x3a, 0x2e, 0xf7, 0xd0, 0xcc, 0xa9, 0x88, 0x72, 0x8c, 0x35, 0xb9, 0x87,
	0x64, 0x1d, 0x72, 0xa3, 0x01, 0x0f, 0xd0, 0xcc, 0x2b, 0x9b, 0xde, 0x48, 0x14, 0x7d, 0xca, 0x86,
	0x66, 0x41, 0xa3, 0x6a, 0x23, 0xd1, 0x48, 0x50, 0x81, 0x66, 0x51, 0x5d, 0xa1, 0x37, 0xe4, 0x01,
	0x00, 0xf3, 0x1c, 0x97, 0x86, 0x9e, 0x13, 0x70, 0xb3, 0xa4, 0x49, 0x31, 0xaf, 0x49, 0x43, 0xef,
	0x94, 0x13, 0x13, 0x0a, 0x2c, 0x98, 0x30, 0x81, 0xa1, 0x09, 0x2a, 0xcd, 0x64, 0x2b, 0xc9, 0xc5,
	0x4b, 0x4d, 0xae, 0xac, 0xc9, 0xc5, 0x98, 0x22, 0xa7, 0xf8, 0x07, 0x82, 0xba, 0xc2, 0xa1, 0x9e,
	0x17, 0x9a, 0xab, 0x09, 0x7f, 0x85, 0x35, 0x3c, 0x2f, 0x94, 0x49, 0xd3, 0x3e, 0x9a, 0x6b, 0x3a,
	0x69, 0xda, 0x47, 0xb2, 0x05, 0x65, 0x37, 0x44, 0x2a, 0xd0, 0x11, 0xcc, 0x47, 0xb3, 0xa2, 0x62,
	0x40, 0x43, 0x5d, 0xe6, 0x2b, 0x87, 0xf1, 0xc8, 0x4b, 0x1d, 0xee, 0x68, 0x07, 0x0d, 0x49, 0x07,
	0x8b, 0xc1, 0x7b, 0x33, 0x6f, 0x19, 0x8d, 0x78, 0x10, 0x21, 0x79, 0x02, 0x79, 0x5d, 0x0f, 0xea,
	0xc1, 0xca, 0x87, 0x77, 0x0f, 0x74, 0x1d, 0x35, 0x15, 0x98, 0xb8, 0xd9, 0xb1, 0x13, 0xd9, 0x81,
	0x2c, 0x0b, 0x5e, 0x70, 0xf5, 0x88, 0xe5, 0xc3, 0x3b, 0xb1, 0x73, 0x7a, 0xaa, 0x32, 0x5a, 0xff,
	0x1a, 0x70, 0xf7, 0x04, 0x43, 0x77, 0x40, 0x03, 0x11, 0x9d, 0x50, 0x81, 0x21, 0xa3, 0xc3, 0x25,
	0xb5, 0xb1, 0x05, 0x65, 0x3f, 0xf6, 0x48, 0x8a, 0x23, 0x63, 0x43, 0x02, 0xb5, 0x3d, 0xb2, 0x03,
	0x6b, 0x21, 0xf6, 0x59, 0x24, 0x25, 0x55, 0x7a, 0xe9, 0x0a, 0x59, 0x4d, 0x40, 0x25, 0xd8, 0x63,
	0xa8, 0x0c, 0x90, 0x0e, 0xc5, 0x20, 0x7d, 0xb2, 0xac, 0xf6, 0xd2, 0x68, 0xfc, 0x6c, 0x35, 0x28,
	0x32, 0x0f, 0x03, 0xc1, 0xc4, 0xa5, 0xaa, 0x9a, 0x9c, 0x9d, 0xee, 0xaf, 0xcb, 0x20, 0x3f, 0x5d,
	0x06, 0x0f, 0xa1, 0x2c, 0xe8, 0x45, 0x7a, 0xa8, 0x2e, 0x9c, 0x92, 0xa0, 0x17, 0xfa, 0x44, 0xeb,
	0x17, 0x03, 0xcc, 0xb9, 0x4c, 0x93, 0x3e, 0x79, 0x1a, 0x6b, 0xa5, 0x85, 0x7d, 0x10, 0x6b, 0xb5,
	0x50, 0x18, 0x2d, 0x1c, 0xf9, 0x04, 0x2a, 0x7c, 0x84, 0xa1, 0xea, 0x41, 0x47, 0x5c, 0x8e, 0x50,
	0xe9, 0x51, 0x39, 0x5c, 0x8f, 0x63, 0xcf, 0x12, 0x63, 0xf7, 0x72, 0x84, 0xf6, 0x1a, 0x9f, 0xde,
	0x5a, 0xe7, 0x70, 0x7f, 0x01, 0x95, 0xdb, 0x3d, 0xf3, 0xdb, 0x5e, 0xc5, 0x3a, 0x82, 0x8d, 0xe7,
	0x28, 0x96, 0xa6, 0xfe, 0x5a, 0xbc, 0x31, 0x17, 0xff, 0x23, 0x3c, 0x58, 0x1c, 0x7f, 0x3b, 0xbe,
	0x4f, 0x67, 0xca, 0xf2, 0x06, 0x52, 0x5b, 0xdf, 0xc3, 0x66, 0x6a, 0x6e, 0x44, 0x11, 0x77, 0x19,
	0x15, 0xd8, 0x19, 0xf0, 0xd1, 0x4d, 0x53, 0x20, 0xf7, 0xa0, 0x10, 0x0d, 0xf8, 0xe8, 0x5a, 0x9f,
	0xbc, 0xdc, 0xb6, 0x3d, 0x35, 0x03, 0x22, 0x87, 0x26, 0x87, 0xaa, 0x82, 0x2d, 0xda, 0x65, 0x76,
	0x7d, 0x8f, 0x75, 0x06, 0x0f, 0x97, 0xdd, 0x7e, 0x2b, 0x01, 0xac, 0x6f, 0xa7, 0xd2, 0x49, 0xb2,
	0x6d, 0x8c, 0x3d, 0x26, 0x6e, 0x9c, 0xce, 0x06, 0x94, 0xa8, 0x0c, 0x70, 0xc6, 0x69, 0x42, 0x45,
	0x05, 0xf4, 0x98, 0x27, 0x07, 0x9e, 0xbc, 0x08, 0x03, 0x11, 0xb7, 0x5f, 0xb2, 0xb5, 0xfe, 0x30,
	0xa6, 0x52, 0x79, 0xed, 0xe6, 0xdb, 0xbd, 0x65, 0xda, 0x89, 0x2b, 0xd3, 0x9d, 0xb8, 0x94, 0x81,
	0xec, 0xfd, 0x00, 0x2f, 0x84, 0x73, 0xcd, 0x3e, 0xab, 0xd8, 0xaf, 0x4a, 0xb4, 0x91, 0x64, 0x70,
	0x0f, 0x0a, 0x2c, 0x72, 0xf8, 0x04, 0x43, 0xd5, 0xfa, 0x45, 0x3b, 0xcf, 0xa2, 0xb3, 0x09, 0x86,
	0xd6, 0xa7, 0x50, 0x99, 0x25, 0x42, 0x2c, 0xc8, 0xaa, 0xd9, 0x6d, 0xa8, 0xde, 0xab, 0xc4, 0x6c,
	0x6d, 0x14, 0x72, 0x7c, 0xdb, 0xca, 0x26, 0x07, 0x99, 0x1f, 0xf5, 0xe3, 0xff, 0x32, 0xb9, 0xdc,
	0xff, 0x0e, 0x0a, 0xb1, 0x0b, 0x29, 0x43, 0xa1, 0xd3, 0x6b, 0x36, 0x5b, 0x9d, 0x4e, 0xf5, 0x1d,
	0x02, 0x90, 0x6b, 0xd9, 0xf6, 0x99, 0x5d, 0xfd, 0x2f, 0x43, 0xd6, 0xa1, 0xd2, 0xeb, 0xb4, 0x6c,
	0xe7, 0xf4, 0xac, 0xeb, 0xb4, 0xbe, 0x6c, 0x77, 0xba, 0xd5, 0x3f, 0xaf, 0x32, 0xa4, 0x0a, 0xa0,
	0x50, 0x8d, 0xfc, 0x75, 0x95, 0x21, 0x26, 0x90, 0x93, 0x96, 0xdd, 0xfc, 0xac, 0x71, 0xda, 0x9d,
	0xf2, 0x7d, 0x75, 0xa5, 0x4e, 0x48, 0x2d, 0x1a, 0xfd, 0xfb, 0x2a, 0xb3, 0x7f, 0x04, 0x6b, 0x33,
	0xa3, 0x81, 0x00, 0xe4, 0x9b, 0x76, 0xab, 0xd1, 0x6d, 0x29, 0x02, 0xf9, 0xde, 0x17, 0xc7, 0x72,
	0x6d, 0xc8, 0xf5, 0x71, 0xeb, 0xf3, 0x56, 0xb7, 0x55, 0x5d, 0x21, 0x25, 0xc8, 0x35, 0x7a, 0xc7,
	0xed, 0x6e, 0x35, 0x73, 0x78, 0x0e, 0xab, 0x72, 0x84, 0x47, 0x1d, 0x0c, 0x27, 0xcc, 0x45, 0xf2,
	0x15, 0x94, 0xa7, 0xfe, 0x2b, 0xc8, 0xfd, 0x58, 0x82, 0xf9, 0x6f, 0x81, 0x5a, 0x6d, 0x91, 0x49,
	0xeb, 0x68, 0xdd, 0xfd, 0xe9, 0xd5, 0x3f, 0x2f, 0x57, 0xee, 0x90, 0xb5, 0xfa, 0xe4, 0x23, 0xf5,
	0x75, 0x52, 0x97, 0x9d, 0x77, 0xf8, 0x7b, 0x16, 0xaa, 0x69, 0xc5, 0x24, 0x37, 0xfe, 0x00, 0xef,
	0xce, 0x55, 0x11, 0xd9, 0x5a, 0xd6, 0xc7, 0xc9, 0xed, 0xdb, 0xcb, 0x1d, 0x62, 0x0e, 0xbb, 0x8a,
	0xc3, 0xb6, 0xb5, 0x91, 0x72, 0xf0, 0x13, 0xdf, 0x7a, 0x52, 0xfc, 0xcf, 0x8c, 0x7d, 0xf2, 0xab,
	0x01, 0xef, 0x2f, 0x2e, 0x63, 0xf2, 0x78, 0xd9, 0x25, 0xd3, 0xfd, 0x55, 0xfb, 0xe0, 0x2d, 0x5e,
	0x31, 0x9f, 0x1d, 0xc5, 0x67, 0xb3, 0x66, 0x2e, 0xe0, 0xa3, 0x0a, 0x58, 0x92, 0xf9, 0xd9, 0x80,
	0xf5, 0x45, 0xd3, 0x91, 0x58, 0xd7, 0x6a, 0x2f, 0xd5, 0x64, 0xe7, 0x8d, 0x3e, 0xb3, 0x34, 0xc8,
	0x9b, 0x64, 0x21, 0x2f, 0xa7, 0x35, 0x99, 0x99, 0x52, 0xf3, 0x9a, 0x2c, 0x1a, 0xa1, 0xf3, 0x9a,
	0x2c, 0x1c, 0x75, 0xd6, 0x87, 0x8a, 0xcc, 0x6e, 0xed, 0xd1, 0x22, 0x4d, 0x92, 0x88, 0xba, 0x1c,
	0xae, 0xcf, 0x8c, 0xfd, 0xaf, 0xf3, 0xea, 0xd3, 0xf4, 0xe3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x16, 0x6c, 0xc7, 0x20, 0x13, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the internal API for UsersService service.
type UsersServiceServer interface {
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UsersService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_users_proto/users/users.proto",
}

// MerchantsServiceClient is the client API for MerchantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsServiceClient interface {
	// 商户提交资料
	MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error)
}

type merchantsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantsServiceClient(cc *grpc.ClientConn) MerchantsServiceClient {
	return &merchantsServiceClient{cc}
}

func (c *merchantsServiceClient) MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error) {
	out := new(MerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error) {
	out := new(MerchantsMaterialAuditResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterialAudit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error) {
	out := new(GetMerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/GetMerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error) {
	out := new(MerchantsAssociateShopResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsAssociateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServiceServer is the internal API for MerchantsService service.
type MerchantsServiceServer interface {
	// 商户提交资料
	MerchantsMaterial(context.Context, *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(context.Context, *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(context.Context, *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(context.Context, *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error)
}

// UnimplementedMerchantsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServiceServer struct {
}

func (*UnimplementedMerchantsServiceServer) MerchantsMaterial(ctx context.Context, req *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsMaterialAudit(ctx context.Context, req *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterialAudit not implemented")
}
func (*UnimplementedMerchantsServiceServer) GetMerchantsMaterial(ctx context.Context, req *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsAssociateShop(ctx context.Context, req *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsAssociateShop not implemented")
}

func RegisterMerchantsServiceServer(s *grpc.Server, srv MerchantsServiceServer) {
	s.RegisterService(&_MerchantsService_serviceDesc, srv)
}

func _MerchantsService_MerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, req.(*MerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsMaterialAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterialAudit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, req.(*MerchantsMaterialAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_GetMerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/GetMerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, req.(*GetMerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsAssociateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsAssociateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsAssociateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, req.(*MerchantsAssociateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.MerchantsService",
	HandlerType: (*MerchantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantsMaterial",
			Handler:    _MerchantsService_MerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsMaterialAudit",
			Handler:    _MerchantsService_MerchantsMaterialAudit_Handler,
		},
		{
			MethodName: "GetMerchantsMaterial",
			Handler:    _MerchantsService_GetMerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsAssociateShop",
			Handler:    _MerchantsService_MerchantsAssociateShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_users_proto/users/users.proto",
}
