// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_shop_proto/shop_business/shop_business.proto

package shop_business

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "SHOP_NOT_EXIST",
	50006: "SHOP_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
	"SHOP_NOT_EXIST":     50005,
	"SHOP_EXIST":         50006,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
	OperationType_AUDIT  OperationType = 3
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
}

var OperationType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
	"AUDIT":  3,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{1}
}

type CoinType int32

const (
	CoinType_CNY CoinType = 0
	CoinType_USD CoinType = 1
	CoinType_HKD CoinType = 2
	CoinType_EUR CoinType = 3
)

var CoinType_name = map[int32]string{
	0: "CNY",
	1: "USD",
	2: "HKD",
	3: "EUR",
}

var CoinType_value = map[string]int32{
	"CNY": 0,
	"USD": 1,
	"HKD": 2,
	"EUR": 3,
}

func (x CoinType) String() string {
	return proto.EnumName(CoinType_name, int32(x))
}

func (CoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{2}
}

type ShopMaterial struct {
	ShopId               int64    `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	MerchantId           int64    `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	RegisterAddr         string   `protobuf:"bytes,5,opt,name=register_addr,json=registerAddr,proto3" json:"register_addr,omitempty"`
	BusinessAddr         string   `protobuf:"bytes,6,opt,name=business_addr,json=businessAddr,proto3" json:"business_addr,omitempty"`
	BusinessLicense      string   `protobuf:"bytes,7,opt,name=business_license,json=businessLicense,proto3" json:"business_license,omitempty"`
	TaxCardNo            string   `protobuf:"bytes,8,opt,name=tax_card_no,json=taxCardNo,proto3" json:"tax_card_no,omitempty"`
	BusinessDesc         string   `protobuf:"bytes,9,opt,name=business_desc,json=businessDesc,proto3" json:"business_desc,omitempty"`
	SocialCreditCode     string   `protobuf:"bytes,10,opt,name=social_credit_code,json=socialCreditCode,proto3" json:"social_credit_code,omitempty"`
	OrganizationCode     string   `protobuf:"bytes,11,opt,name=organization_code,json=organizationCode,proto3" json:"organization_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopMaterial) Reset()         { *m = ShopMaterial{} }
func (m *ShopMaterial) String() string { return proto.CompactTextString(m) }
func (*ShopMaterial) ProtoMessage()    {}
func (*ShopMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{0}
}

func (m *ShopMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopMaterial.Unmarshal(m, b)
}
func (m *ShopMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopMaterial.Marshal(b, m, deterministic)
}
func (m *ShopMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopMaterial.Merge(m, src)
}
func (m *ShopMaterial) XXX_Size() int {
	return xxx_messageInfo_ShopMaterial.Size(m)
}
func (m *ShopMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_ShopMaterial proto.InternalMessageInfo

func (m *ShopMaterial) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopMaterial) GetMerchantId() int64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *ShopMaterial) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ShopMaterial) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *ShopMaterial) GetRegisterAddr() string {
	if m != nil {
		return m.RegisterAddr
	}
	return ""
}

func (m *ShopMaterial) GetBusinessAddr() string {
	if m != nil {
		return m.BusinessAddr
	}
	return ""
}

func (m *ShopMaterial) GetBusinessLicense() string {
	if m != nil {
		return m.BusinessLicense
	}
	return ""
}

func (m *ShopMaterial) GetTaxCardNo() string {
	if m != nil {
		return m.TaxCardNo
	}
	return ""
}

func (m *ShopMaterial) GetBusinessDesc() string {
	if m != nil {
		return m.BusinessDesc
	}
	return ""
}

func (m *ShopMaterial) GetSocialCreditCode() string {
	if m != nil {
		return m.SocialCreditCode
	}
	return ""
}

func (m *ShopMaterial) GetOrganizationCode() string {
	if m != nil {
		return m.OrganizationCode
	}
	return ""
}

type GetShopMaterialRequest struct {
	ShopId               int64    `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopMaterialRequest) Reset()         { *m = GetShopMaterialRequest{} }
func (m *GetShopMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopMaterialRequest) ProtoMessage()    {}
func (*GetShopMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{1}
}

func (m *GetShopMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopMaterialRequest.Unmarshal(m, b)
}
func (m *GetShopMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopMaterialRequest.Marshal(b, m, deterministic)
}
func (m *GetShopMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopMaterialRequest.Merge(m, src)
}
func (m *GetShopMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopMaterialRequest.Size(m)
}
func (m *GetShopMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopMaterialRequest proto.InternalMessageInfo

func (m *GetShopMaterialRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetShopMaterialResponse struct {
	Material             *ShopMaterial `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetShopMaterialResponse) Reset()         { *m = GetShopMaterialResponse{} }
func (m *GetShopMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*GetShopMaterialResponse) ProtoMessage()    {}
func (*GetShopMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{2}
}

func (m *GetShopMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopMaterialResponse.Unmarshal(m, b)
}
func (m *GetShopMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopMaterialResponse.Marshal(b, m, deterministic)
}
func (m *GetShopMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopMaterialResponse.Merge(m, src)
}
func (m *GetShopMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_GetShopMaterialResponse.Size(m)
}
func (m *GetShopMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopMaterialResponse proto.InternalMessageInfo

func (m *GetShopMaterialResponse) GetMaterial() *ShopMaterial {
	if m != nil {
		return m.Material
	}
	return nil
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=shop_business.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{3}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ShopPledgeRequest struct {
	OpUid                int64    `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
	OpIp                 string   `protobuf:"bytes,2,opt,name=op_ip,json=opIp,proto3" json:"op_ip,omitempty"`
	ShopId               int64    `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CoinType             CoinType `protobuf:"varint,5,opt,name=coin_type,json=coinType,proto3,enum=shop_business.CoinType" json:"coin_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopPledgeRequest) Reset()         { *m = ShopPledgeRequest{} }
func (m *ShopPledgeRequest) String() string { return proto.CompactTextString(m) }
func (*ShopPledgeRequest) ProtoMessage()    {}
func (*ShopPledgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{4}
}

func (m *ShopPledgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopPledgeRequest.Unmarshal(m, b)
}
func (m *ShopPledgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopPledgeRequest.Marshal(b, m, deterministic)
}
func (m *ShopPledgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopPledgeRequest.Merge(m, src)
}
func (m *ShopPledgeRequest) XXX_Size() int {
	return xxx_messageInfo_ShopPledgeRequest.Size(m)
}
func (m *ShopPledgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopPledgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShopPledgeRequest proto.InternalMessageInfo

func (m *ShopPledgeRequest) GetOpUid() int64 {
	if m != nil {
		return m.OpUid
	}
	return 0
}

func (m *ShopPledgeRequest) GetOpIp() string {
	if m != nil {
		return m.OpIp
	}
	return ""
}

func (m *ShopPledgeRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopPledgeRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ShopPledgeRequest) GetCoinType() CoinType {
	if m != nil {
		return m.CoinType
	}
	return CoinType_CNY
}

type ShopPledgeResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	State                int32           `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShopPledgeResponse) Reset()         { *m = ShopPledgeResponse{} }
func (m *ShopPledgeResponse) String() string { return proto.CompactTextString(m) }
func (*ShopPledgeResponse) ProtoMessage()    {}
func (*ShopPledgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{5}
}

func (m *ShopPledgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopPledgeResponse.Unmarshal(m, b)
}
func (m *ShopPledgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopPledgeResponse.Marshal(b, m, deterministic)
}
func (m *ShopPledgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopPledgeResponse.Merge(m, src)
}
func (m *ShopPledgeResponse) XXX_Size() int {
	return xxx_messageInfo_ShopPledgeResponse.Size(m)
}
func (m *ShopPledgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopPledgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShopPledgeResponse proto.InternalMessageInfo

func (m *ShopPledgeResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ShopPledgeResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type ShopApplyRequest struct {
	OperationType        OperationType `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=shop_business.OperationType" json:"operation_type,omitempty"`
	OpUid                int64         `protobuf:"varint,2,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
	OpIp                 string        `protobuf:"bytes,3,opt,name=op_ip,json=opIp,proto3" json:"op_ip,omitempty"`
	ShopId               int64         `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	MerchantId           int64         `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	NickName             string        `protobuf:"bytes,6,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	FullName             string        `protobuf:"bytes,7,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	RegisterAddr         string        `protobuf:"bytes,8,opt,name=register_addr,json=registerAddr,proto3" json:"register_addr,omitempty"`
	BusinessAddr         string        `protobuf:"bytes,9,opt,name=business_addr,json=businessAddr,proto3" json:"business_addr,omitempty"`
	BusinessLicense      string        `protobuf:"bytes,10,opt,name=business_license,json=businessLicense,proto3" json:"business_license,omitempty"`
	TaxCardNo            string        `protobuf:"bytes,11,opt,name=tax_card_no,json=taxCardNo,proto3" json:"tax_card_no,omitempty"`
	BusinessDesc         string        `protobuf:"bytes,12,opt,name=business_desc,json=businessDesc,proto3" json:"business_desc,omitempty"`
	SocialCreditCode     string        `protobuf:"bytes,13,opt,name=social_credit_code,json=socialCreditCode,proto3" json:"social_credit_code,omitempty"`
	OrganizationCode     string        `protobuf:"bytes,14,opt,name=organization_code,json=organizationCode,proto3" json:"organization_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShopApplyRequest) Reset()         { *m = ShopApplyRequest{} }
func (m *ShopApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ShopApplyRequest) ProtoMessage()    {}
func (*ShopApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{6}
}

func (m *ShopApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopApplyRequest.Unmarshal(m, b)
}
func (m *ShopApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopApplyRequest.Marshal(b, m, deterministic)
}
func (m *ShopApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopApplyRequest.Merge(m, src)
}
func (m *ShopApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ShopApplyRequest.Size(m)
}
func (m *ShopApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShopApplyRequest proto.InternalMessageInfo

func (m *ShopApplyRequest) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_CREATE
}

func (m *ShopApplyRequest) GetOpUid() int64 {
	if m != nil {
		return m.OpUid
	}
	return 0
}

func (m *ShopApplyRequest) GetOpIp() string {
	if m != nil {
		return m.OpIp
	}
	return ""
}

func (m *ShopApplyRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopApplyRequest) GetMerchantId() int64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *ShopApplyRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ShopApplyRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *ShopApplyRequest) GetRegisterAddr() string {
	if m != nil {
		return m.RegisterAddr
	}
	return ""
}

func (m *ShopApplyRequest) GetBusinessAddr() string {
	if m != nil {
		return m.BusinessAddr
	}
	return ""
}

func (m *ShopApplyRequest) GetBusinessLicense() string {
	if m != nil {
		return m.BusinessLicense
	}
	return ""
}

func (m *ShopApplyRequest) GetTaxCardNo() string {
	if m != nil {
		return m.TaxCardNo
	}
	return ""
}

func (m *ShopApplyRequest) GetBusinessDesc() string {
	if m != nil {
		return m.BusinessDesc
	}
	return ""
}

func (m *ShopApplyRequest) GetSocialCreditCode() string {
	if m != nil {
		return m.SocialCreditCode
	}
	return ""
}

func (m *ShopApplyRequest) GetOrganizationCode() string {
	if m != nil {
		return m.OrganizationCode
	}
	return ""
}

type ShopApplyResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	ShopId               int64           `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShopApplyResponse) Reset()         { *m = ShopApplyResponse{} }
func (m *ShopApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ShopApplyResponse) ProtoMessage()    {}
func (*ShopApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68caca7b53d1624d, []int{7}
}

func (m *ShopApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopApplyResponse.Unmarshal(m, b)
}
func (m *ShopApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopApplyResponse.Marshal(b, m, deterministic)
}
func (m *ShopApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopApplyResponse.Merge(m, src)
}
func (m *ShopApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ShopApplyResponse.Size(m)
}
func (m *ShopApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShopApplyResponse proto.InternalMessageInfo

func (m *ShopApplyResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ShopApplyResponse) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func init() {
	proto.RegisterEnum("shop_business.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("shop_business.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("shop_business.CoinType", CoinType_name, CoinType_value)
	proto.RegisterType((*ShopMaterial)(nil), "shop_business.ShopMaterial")
	proto.RegisterType((*GetShopMaterialRequest)(nil), "shop_business.GetShopMaterialRequest")
	proto.RegisterType((*GetShopMaterialResponse)(nil), "shop_business.GetShopMaterialResponse")
	proto.RegisterType((*CommonResponse)(nil), "shop_business.CommonResponse")
	proto.RegisterType((*ShopPledgeRequest)(nil), "shop_business.ShopPledgeRequest")
	proto.RegisterType((*ShopPledgeResponse)(nil), "shop_business.ShopPledgeResponse")
	proto.RegisterType((*ShopApplyRequest)(nil), "shop_business.ShopApplyRequest")
	proto.RegisterType((*ShopApplyResponse)(nil), "shop_business.ShopApplyResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_shop_proto/shop_business/shop_business.proto", fileDescriptor_68caca7b53d1624d)
}

var fileDescriptor_68caca7b53d1624d = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdf, 0x8e, 0xdb, 0xc4,
	0x17, 0x6e, 0xe2, 0xfc, 0x3d, 0xd9, 0xa4, 0xee, 0xb4, 0xbf, 0xdd, 0x28, 0x6d, 0x7f, 0xbb, 0x35,
	0x02, 0x96, 0x00, 0x1b, 0x75, 0x01, 0x21, 0x21, 0x51, 0x29, 0x38, 0x16, 0x1b, 0xd1, 0x66, 0x57,
	0x76, 0x22, 0xc1, 0x95, 0x35, 0xb5, 0x87, 0xec, 0xa8, 0xb6, 0xc7, 0xd8, 0xce, 0xd2, 0x85, 0x3b,
	0x2e, 0x56, 0x42, 0xe2, 0x8e, 0x8b, 0xde, 0x73, 0xc1, 0xfb, 0x40, 0x81, 0x27, 0xe0, 0x11, 0x78,
	0x00, 0x34, 0x33, 0x76, 0xb0, 0xd3, 0x64, 0x77, 0x11, 0x77, 0x67, 0xbe, 0xf3, 0xe5, 0x9c, 0x39,
	0x7f, 0x3e, 0x4f, 0xe0, 0xe3, 0x30, 0x62, 0x09, 0x1b, 0xf8, 0xd4, 0x89, 0x98, 0xed, 0x63, 0xcf,
	0xb3, 0xe3, 0x53, 0x16, 0xda, 0x12, 0x15, 0xe6, 0xd3, 0x45, 0x4c, 0x03, 0x12, 0xc7, 0xc5, 0xd3,
	0x81, 0x60, 0xa0, 0x76, 0x01, 0xec, 0x3d, 0x9a, 0xd3, 0x84, 0x90, 0x03, 0x87, 0xf9, 0x83, 0x67,
	0xc4, 0x3b, 0xa3, 0x41, 0xfc, 0x2e, 0x65, 0x03, 0x87, 0xf9, 0x3e, 0x0b, 0x06, 0x32, 0xe6, 0x9c,
	0xb1, 0xb9, 0x47, 0x06, 0x38, 0xa4, 0x03, 0x1c, 0x04, 0x2c, 0xc1, 0x09, 0x65, 0x41, 0x1a, 0x4e,
	0x7b, 0xa1, 0xc0, 0x96, 0x75, 0xca, 0xc2, 0x27, 0x38, 0x21, 0x11, 0xc5, 0x1e, 0xda, 0x81, 0xba,
	0xc8, 0x40, 0xdd, 0x6e, 0x69, 0xaf, 0xb4, 0xaf, 0x98, 0x35, 0x7e, 0x1c, 0xbb, 0x68, 0x17, 0x5a,
	0x3e, 0x89, 0x9c, 0x53, 0x1c, 0x24, 0xdc, 0x59, 0x16, 0x4e, 0xc8, 0xa0, 0xb1, 0x8b, 0xee, 0x42,
	0x33, 0xa0, 0xce, 0x33, 0x3b, 0xc0, 0x3e, 0xe9, 0x2a, 0x7b, 0xa5, 0xfd, 0xa6, 0xd9, 0xe0, 0xc0,
	0x04, 0xfb, 0x84, 0x3b, 0xbf, 0x5c, 0x78, 0x9e, 0x74, 0x56, 0xa4, 0x93, 0x03, 0xc2, 0xf9, 0x1a,
	0xb4, 0x23, 0x32, 0xa7, 0x71, 0x42, 0x22, 0x1b, 0xbb, 0x6e, 0xd4, 0xad, 0x0a, 0xc2, 0x56, 0x06,
	0x0e, 0x5d, 0x37, 0xe2, 0xa4, 0xac, 0x6a, 0x49, 0xaa, 0x49, 0x52, 0x06, 0x0a, 0xd2, 0x5b, 0xa0,
	0x2e, 0x49, 0x1e, 0x75, 0x48, 0x10, 0x93, 0x6e, 0x5d, 0xf0, 0x6e, 0x66, 0xf8, 0x63, 0x09, 0xa3,
	0xff, 0x43, 0x2b, 0xc1, 0xcf, 0x6d, 0x07, 0x47, 0xae, 0x1d, 0xb0, 0x6e, 0x43, 0xb0, 0x9a, 0x09,
	0x7e, 0xae, 0xe3, 0xc8, 0x9d, 0xb0, 0x42, 0x3e, 0x97, 0xc4, 0x4e, 0xb7, 0x59, 0xcc, 0x37, 0x22,
	0xb1, 0x83, 0xde, 0x01, 0x14, 0x33, 0x87, 0x62, 0xcf, 0x76, 0x22, 0xe2, 0xd2, 0xc4, 0x76, 0x98,
	0x4b, 0xba, 0x20, 0x98, 0xaa, 0xf4, 0xe8, 0xc2, 0xa1, 0x33, 0x97, 0xa0, 0xb7, 0xe1, 0x16, 0x8b,
	0xe6, 0x38, 0xa0, 0xdf, 0x88, 0x19, 0x48, 0x72, 0x4b, 0x92, 0xf3, 0x0e, 0x4e, 0xd6, 0x1e, 0xc2,
	0xf6, 0xa7, 0x24, 0xc9, 0xcf, 0xc6, 0x24, 0x5f, 0x2d, 0x48, 0x9c, 0x6c, 0x1c, 0x91, 0x66, 0xc2,
	0xce, 0x2b, 0x3f, 0x89, 0x43, 0xc6, 0xab, 0xfd, 0x10, 0x1a, 0x7e, 0x8a, 0x89, 0x1f, 0xb5, 0x0e,
	0xef, 0x1e, 0x14, 0xd7, 0xab, 0xf0, 0xb3, 0x25, 0x59, 0x9b, 0x40, 0x47, 0x17, 0xdb, 0xb4, 0x0c,
	0xd5, 0x87, 0x8a, 0xb8, 0x38, 0x0f, 0xd3, 0x39, 0xdc, 0x5e, 0x09, 0x63, 0x12, 0x51, 0xab, 0x29,
	0x38, 0x48, 0x05, 0xc5, 0x8f, 0xe7, 0x62, 0x59, 0x9a, 0x26, 0x37, 0xb5, 0x9f, 0x4b, 0x70, 0x8b,
	0xa7, 0x3a, 0xf1, 0x88, 0x3b, 0x27, 0x59, 0x49, 0xff, 0x83, 0x1a, 0x0b, 0xed, 0xc5, 0xb2, 0xa2,
	0x2a, 0x0b, 0x67, 0xd4, 0x45, 0xb7, 0xa1, 0xca, 0xeb, 0x0c, 0xd3, 0x00, 0x15, 0x16, 0x8e, 0xc3,
	0x7c, 0xf9, 0x4a, 0x61, 0x43, 0xb7, 0xa1, 0x86, 0x7d, 0xb6, 0x08, 0x92, 0x74, 0xc1, 0xd2, 0x13,
	0x7a, 0x1f, 0x9a, 0x0e, 0xa3, 0x81, 0x9d, 0x9c, 0x87, 0x44, 0xac, 0x56, 0xe7, 0x70, 0x67, 0xe5,
	0xd6, 0x3a, 0xa3, 0xc1, 0xf4, 0x3c, 0x24, 0x66, 0xc3, 0x49, 0x2d, 0x0d, 0x03, 0xca, 0xdf, 0x33,
	0x2d, 0xfe, 0x03, 0xa8, 0x49, 0x71, 0xa5, 0x5d, 0xbc, 0xff, 0x4a, 0xa0, 0x7c, 0xaf, 0xcc, 0x94,
	0x8c, 0xee, 0x40, 0x35, 0x4e, 0x70, 0x42, 0x44, 0x21, 0x55, 0x53, 0x1e, 0xb4, 0x1f, 0x2a, 0xa0,
	0xf2, 0x1c, 0xc3, 0x30, 0xf4, 0xce, 0xb3, 0x56, 0xe8, 0xd0, 0x61, 0x21, 0x89, 0xe4, 0x86, 0x88,
	0x2b, 0xcb, 0x46, 0xdf, 0x5b, 0xc9, 0x74, 0x9c, 0x91, 0xc4, 0xbd, 0xdb, 0x2c, 0x7f, 0xcc, 0xf5,
	0xb3, 0xbc, 0xb6, 0x9f, 0xca, 0xfa, 0x7e, 0x56, 0x2e, 0x53, 0x7c, 0xf5, 0x72, 0xc5, 0xd7, 0x2e,
	0x53, 0x7c, 0xfd, 0x2a, 0xc5, 0x37, 0xae, 0xa3, 0xf8, 0xe6, 0x35, 0x15, 0x0f, 0xd7, 0x52, 0x7c,
	0xeb, 0x4a, 0xc5, 0x6f, 0x5d, 0x5b, 0xf1, 0xed, 0x7f, 0xa3, 0xf8, 0xce, 0x06, 0xc5, 0x3b, 0x52,
	0x19, 0xe9, 0x36, 0xfc, 0xb7, 0x85, 0xcb, 0x0d, 0xb5, 0x9c, 0x1f, 0x6a, 0xff, 0xa7, 0x12, 0xd4,
	0x53, 0x8d, 0xa2, 0x16, 0xd4, 0xad, 0x99, 0xae, 0x1b, 0x96, 0xa5, 0xde, 0x40, 0x00, 0x55, 0xc3,
	0x34, 0x8f, 0x4d, 0xf5, 0x2f, 0x05, 0xdd, 0x81, 0xce, 0xcc, 0x32, 0x4c, 0x7b, 0x72, 0x3c, 0xb5,
	0x8d, 0xcf, 0xc7, 0xd6, 0x54, 0xfd, 0xe5, 0x42, 0x41, 0x2a, 0x80, 0x40, 0x25, 0xf2, 0xeb, 0x85,
	0x82, 0xba, 0x80, 0x9e, 0x18, 0xa6, 0x7e, 0x34, 0x9c, 0x4c, 0x73, 0xdc, 0x97, 0x17, 0x22, 0xc2,
	0xd2, 0x23, 0xd1, 0xdf, 0x24, 0x6a, 0x1d, 0x1d, 0x9f, 0xe4, 0xb8, 0xbf, 0xcb, 0xb8, 0x02, 0x95,
	0xc8, 0x1f, 0x17, 0x4a, 0xff, 0x11, 0xb4, 0x0b, 0xeb, 0x8d, 0x00, 0x6a, 0xba, 0x69, 0x0c, 0xa7,
	0x86, 0xb8, 0x68, 0x6d, 0x76, 0x32, 0xe2, 0x76, 0x89, 0xdb, 0x23, 0xe3, 0xb1, 0x31, 0x35, 0xd4,
	0x32, 0x6a, 0x42, 0x75, 0x38, 0x1b, 0x8d, 0xa7, 0xaa, 0xd2, 0x3f, 0x80, 0x46, 0xa6, 0x68, 0x54,
	0x07, 0x45, 0x9f, 0x7c, 0xa1, 0xde, 0xe0, 0xc6, 0xcc, 0x1a, 0xa9, 0x25, 0x6e, 0x1c, 0x7d, 0x36,
	0x52, 0xcb, 0xdc, 0x30, 0x66, 0xa6, 0xaa, 0x1c, 0xbe, 0x50, 0xe0, 0x36, 0x6f, 0xfd, 0x27, 0x69,
	0x57, 0x2d, 0x12, 0x9d, 0x51, 0x87, 0xa0, 0xaf, 0xa1, 0xb9, 0x9c, 0x08, 0xda, 0x5d, 0xf3, 0xc1,
	0xcc, 0x2b, 0xb7, 0xb7, 0xb7, 0x99, 0x20, 0xa7, 0xa3, 0xbd, 0xf9, 0xdd, 0xcb, 0x3f, 0x7f, 0x2c,
	0x3f, 0xd0, 0xee, 0x0d, 0xce, 0x1e, 0xae, 0x79, 0xeb, 0x07, 0x98, 0xb3, 0x3f, 0x2a, 0xf5, 0xd1,
	0xb7, 0x00, 0xff, 0x7c, 0x7c, 0xd0, 0xba, 0xc0, 0x85, 0xef, 0x67, 0xef, 0xc1, 0x25, 0x8c, 0x34,
	0xf7, 0xbe, 0xc8, 0xad, 0xf5, 0xee, 0x6f, 0xc8, 0x1d, 0x0a, 0x3a, 0x4f, 0xfe, 0x7d, 0x09, 0x6e,
	0xae, 0xbc, 0x23, 0xe8, 0xf5, 0x95, 0x04, 0xeb, 0x9f, 0xa6, 0xde, 0x1b, 0x57, 0xd1, 0x8a, 0x8d,
	0x40, 0xbb, 0x1b, 0x2e, 0x93, 0x3d, 0x3f, 0x4f, 0x6b, 0xe2, 0x6f, 0xca, 0x7b, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x11, 0x1c, 0xa6, 0x36, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShopBusinessServiceClient is the client API for ShopBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopBusinessServiceClient interface {
	// 提交店铺申请材料
	ShopApply(ctx context.Context, in *ShopApplyRequest, opts ...grpc.CallOption) (*ShopApplyResponse, error)
	// 店铺质押保证金
	ShopPledge(ctx context.Context, in *ShopPledgeRequest, opts ...grpc.CallOption) (*ShopPledgeResponse, error)
	// 获取店铺材料
	GetShopMaterial(ctx context.Context, in *GetShopMaterialRequest, opts ...grpc.CallOption) (*GetShopMaterialResponse, error)
}

type shopBusinessServiceClient struct {
	cc *grpc.ClientConn
}

func NewShopBusinessServiceClient(cc *grpc.ClientConn) ShopBusinessServiceClient {
	return &shopBusinessServiceClient{cc}
}

func (c *shopBusinessServiceClient) ShopApply(ctx context.Context, in *ShopApplyRequest, opts ...grpc.CallOption) (*ShopApplyResponse, error) {
	out := new(ShopApplyResponse)
	err := c.cc.Invoke(ctx, "/shop_business.ShopBusinessService/ShopApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopBusinessServiceClient) ShopPledge(ctx context.Context, in *ShopPledgeRequest, opts ...grpc.CallOption) (*ShopPledgeResponse, error) {
	out := new(ShopPledgeResponse)
	err := c.cc.Invoke(ctx, "/shop_business.ShopBusinessService/ShopPledge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopBusinessServiceClient) GetShopMaterial(ctx context.Context, in *GetShopMaterialRequest, opts ...grpc.CallOption) (*GetShopMaterialResponse, error) {
	out := new(GetShopMaterialResponse)
	err := c.cc.Invoke(ctx, "/shop_business.ShopBusinessService/GetShopMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopBusinessServiceServer is the server API for ShopBusinessService service.
type ShopBusinessServiceServer interface {
	// 提交店铺申请材料
	ShopApply(context.Context, *ShopApplyRequest) (*ShopApplyResponse, error)
	// 店铺质押保证金
	ShopPledge(context.Context, *ShopPledgeRequest) (*ShopPledgeResponse, error)
	// 获取店铺材料
	GetShopMaterial(context.Context, *GetShopMaterialRequest) (*GetShopMaterialResponse, error)
}

// UnimplementedShopBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopBusinessServiceServer struct {
}

func (*UnimplementedShopBusinessServiceServer) ShopApply(ctx context.Context, req *ShopApplyRequest) (*ShopApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShopApply not implemented")
}
func (*UnimplementedShopBusinessServiceServer) ShopPledge(ctx context.Context, req *ShopPledgeRequest) (*ShopPledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShopPledge not implemented")
}
func (*UnimplementedShopBusinessServiceServer) GetShopMaterial(ctx context.Context, req *GetShopMaterialRequest) (*GetShopMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopMaterial not implemented")
}

func RegisterShopBusinessServiceServer(s *grpc.Server, srv ShopBusinessServiceServer) {
	s.RegisterService(&_ShopBusinessService_serviceDesc, srv)
}

func _ShopBusinessService_ShopApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopBusinessServiceServer).ShopApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop_business.ShopBusinessService/ShopApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopBusinessServiceServer).ShopApply(ctx, req.(*ShopApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopBusinessService_ShopPledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopPledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopBusinessServiceServer).ShopPledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop_business.ShopBusinessService/ShopPledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopBusinessServiceServer).ShopPledge(ctx, req.(*ShopPledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopBusinessService_GetShopMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopBusinessServiceServer).GetShopMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop_business.ShopBusinessService/GetShopMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopBusinessServiceServer).GetShopMaterial(ctx, req.(*GetShopMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop_business.ShopBusinessService",
	HandlerType: (*ShopBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShopApply",
			Handler:    _ShopBusinessService_ShopApply_Handler,
		},
		{
			MethodName: "ShopPledge",
			Handler:    _ShopBusinessService_ShopPledge_Handler,
		},
		{
			MethodName: "GetShopMaterial",
			Handler:    _ShopBusinessService_GetShopMaterial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_shop_proto/shop_business/shop_business.proto",
}
